### PR TITLE
Removes unnecessay activator from CSS plug-in

### PR DESCRIPTION
**Pull request by vogella**
To keep the Java package in Git, an emptry .gitignore file is added to
the source folder. Alternatively the source folder good get removed, as
this is not used / necessary but I wanted to the make the change as
small as possible.

### CODE REVIEW

**Comment by vogella** [comment]
Albert, please review. I assume the Gradle build fails, as we started an unfinished move to Maven.

**Review by de-jcup — APPROVED** [review]
Thanx

**Comment by vogella** [comment]
Can I merge even we have this build error?

**Comment by de-jcup** [comment]
> Can I merge even we have this build error?

Yes. please merge. It's okay, the changes will work. https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/376 will address the problems and I will change this soon.

**Pull request merged**
